version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: change-history-middleware_api
    restart: unless-stopped
    ports:
      - "8088:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - mongodb
    networks:
      - change-history
    environment:
      - MONGO_URI=mongodb://root:admin123@mongodb:27017/change_history
    # # environment:
    # #   APP_NAME: change-history-middleware
    # #   APP_ENV: local
    # #   APP_DEBUG: 'true'
    # #   DB_HOST: change-history-middleware-db
    # #   DB_PORT: 27017
    # #   DB_DATABASE: change_history
    # #   DB_USERNAME: root
    # #   DB_PASSWORD: admin123

  mongodb:
    image: mongo:latest
    container_name: change-history-middleware-db
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongodb_data:/data/db
    networks:
      - change-history
    environment:
      MONGO_INITDB_DATABASE: change_history
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin123
      SERVICE_TAGS: debug
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro  # Mount the initialization script
    command: ["--auth"]  # Enable authentication


  redis:
    image: "redis:alpine"
    container_name: change-history-middleware-redis
    ports:
     - "8087:6379"
    volumes:
      - ./:/var/www/html
    networks:
      - change-history
    

volumes:
  mongodb_data:
  nginx: {}
networks:
  change-history:
    driver: bridge