// import { Inter } from "next/font/google";
import Provider from "@/SessionProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Provider childern={
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      }>
      </Provider>
    </html >
  );
}
